version: '3'

services:

  eventus-api:
    build:
      context: services/api
      dockerfile: Dockerfile.prod
    ports:
      - 3042:3042
  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db